OPENAI_API_KEY = "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"
ANTHROPIC_API_KEY = "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"
